---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 8
    assignees:
      - "jlec"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pre-commit:
        patterns:
          - "*"
    open-pull-requests-limit: 8
    assignees:
      - "jlec"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pip:
        patterns:
          - "*"
    open-pull-requests-limit: 8
    assignees:
      - "jlec"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      uv:
        patterns:
          - "*"
    open-pull-requests-limit: 8
    assignees:
      - "jlec"
